apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accommodation-fe-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - 2306245794-fe.hafizmuh.site # <- Ubah sesuai nama domain kalian
      secretName: fe-hafizmuh-site-tls
  rules:
    - host: 2306245794-fe.hafizmuh.site # <- Ubah sesuai nama domain kalian
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accommodation-fe-service
                port:
                  number: 80